CupCarbon v. Twin IoT 6.52
----------------
name:Reto 2 - Capa de Comunicacion
zoom:0
centerposition_la:5.824521843854751
centerposition_lo:-792.869975566864
map:0
display_details:true
draw_radio_links:true
draw_sensor_arrows:true
radio_links_color:0
draw_marker_arrows:false
display_rl_distance:false
propagation:false
display_marker_distance:false
display_radio_messages:true
draw_script_file_name:true
display_print_messages:true
display_all_routes:false
